MAGETWO-84124: Add bundle parent/child relationship during import
magento-engcom/import-export-improvements pull request #104
Opened 2018-04-25 01:00 UTC by adam-paterson

### Description
* Save parent/child relationships for bundled products during import process.

### Fixed Issues (if relevant)

1. magento/magento2#12330: Imported bundle products are not assigned stock status

### Manual testing scenarios

1. Create Bundled product with options
2. Export product via System -> Import/Export
3. Re-upload CSV choosing "Replace" method

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-04-25 16:27 UTC, dmanners requested changes

2018-04-25 16:27 UTC, dmanners commented on app/code/Magento/BundleImportExport/Model/Import/Product/Type/Bundle/RelationsDataSaver.php
> +        \Magento\Catalog\Model\ResourceModel\Product\Relation $productRelation
Can we make this backwards compatible http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html#adding-a-constructor-parameter

2018-04-26 08:07 UTC, adam-paterson commented on app/code/Magento/BundleImportExport/Model/Import/Product/Type/Bundle/RelationsDataSaver.php
> +        \Magento\Catalog\Model\ResourceModel\Product\Relation $productRelation
On it.

2018-04-27 09:06 UTC, adam-paterson commented on app/code/Magento/BundleImportExport/Model/Import/Product/Type/Bundle/RelationsDataSaver.php
> +        \Magento\Catalog\Model\ResourceModel\Product\Relation $productRelation
@dmanners Added the backwards compatibility change and tests passing.

2018-04-30 09:44 UTC, dmanners requested changes

2018-04-30 09:44 UTC, dmanners commented on app/code/Magento/BundleImportExport/Model/Import/Product/Type/Bundle.php
> +    protected function insertParentChildRelations()
Do we only need this in this class? In that case we should make this private, if it is needed in other places then we should make this public. We are trying to avoid protected in new classes and methods.

2018-04-30 10:15 UTC, adam-paterson commented on app/code/Magento/BundleImportExport/Model/Import/Product/Type/Bundle.php
> +    protected function insertParentChildRelations()
Yep, only in this class. Like we're doing to the NHS; I'll privatise.

2018-05-07 13:28 UTC, dmanners commented
Hi @adam-paterson there seems to have been a change on 2.3 that is now causing a conflict. Any chance you could update your branch and double check that your fix is still working for me before I continue here.

2018-05-17 14:39 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/import-export-improvements?pullRequest=104) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/import-export-improvements?pullRequest=104) before we can accept your contribution.<br/>

2018-05-19 08:39 UTC, adam-paterson commented
@dmanners Rebased, fixed conflicts and tests passing.

2018-05-30 07:20 UTC, merged