Introduce a new configuration field to set the DateTime Format at least for the import/export
magento-engcom/import-export-improvements pull request #114
Opened 2018-06-22 09:08 UTC by ulftietze

This pull request is one step of the general problem, that the import/export is facing, when it's come from export to reimport the same file. One related issue is the #61. This PR fixes one of the reasons, that this could not work.

We ran here into the problem, that the dateformat in standart format looks like eg.
German:  12.11.18 15:42:45
US: 11/12/18 15:42:45

We can't reimport this, because of the PHP "strtotime()" function.
If you called this function with this dateformat, we ran into the issue, that this date could not resolve the "18" as year at the end. Probably PHP tried to lookup for the exact year, and this could be 1918, 2018, 2118, and so on. So this breaks everything.

Now you can set your default datetime in Stores > Configuration > General > Locale > DateTime Format.
It's saved under 'general/locale/locale_date_format'.

### Fixed Issues (if relevant)
1. Probably a small thing of #61 

### Contribution checklist
 - [Y] Pull request has a meaningful description of its purpose
 - [Y] All commits are accompanied by meaningful commit messages
 - [Y] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-22 09:08 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/import-export-improvements?pullRequest=114) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/import-export-improvements?pullRequest=114) before we can accept your contribution.<br/><hr/>**Ulf Tietze** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-06-25 13:59 UTC, dmanners commented
@ulftietze I think your git user and github user are not the same or linked. Could you please check that and get back to me on this.

2018-07-09 09:48 UTC, kokoc requested changes

2018-07-09 09:48 UTC, kokoc commented on lib/internal/Magento/Framework/Stdlib/DateTime/GetDateTimeFormatFromConfigInterface.php
> +interface GetDateTimeFormatFromConfigInterface
I think there are two issues in this class/interface:
- It's designed as a command - thing that changes the state. However, the intent of the interface is to return a format by some scope. Usually, we use `noun::verb` naming for such things.
- `getDefaultDatetimeFormatPath` method is an implementation details. Some implementations of `GetDateTimeFormatFromConfigInterface` may store the datetime formats in DB or files without any XML paths.
- Inteface and class contain a part of namespace in the names.

Considering points above I suggest to drop the `getDefaultDatetimeFormatPath` method from inteface and rename interface + class + `execute` method to something like `Magento\Framework\Stdlib\DateTime\ConfigInterface::getFormat($scopeType, $scopeCode)`

2018-07-09 09:48 UTC, kokoc commented on app/code/Magento/Directory/Helper/Data.php
> +    const XML_PATH_DEFAULT_DATETIME_FORMAT = 'general/locale/locale_date_format';
The implemntation of interface is better place for this constant

2018-07-09 09:48 UTC, kokoc commented on app/code/Magento/Directory/etc/adminhtml/system.xml
> +                <field id="locale_date_format" translate="label" type="text" sortOrder="8" showInDefault="1" showInWebsite="1" showInStore="1">
Currently, there is a circular dependency in Store-Directory modules pair. Any dependencies between these two modules are not welcome according to the desired state. 

This PR defines: interface and implementation in `framework`; constant and system config setting in `Directory` module; di configuration in `Store` module with dependency on `Directory` module.

I suggest to put everything except the interface in `Directory` module. Alternatively, it's possible to have both interface and class in framework, and all other things in `Directory` module.

2018-08-13 03:26 UTC, dmanners commented
Hi @ulftietze I am going to close this PR due to inactivity. If you have time and want to come back to this PR please feel free to address the issues raised in the review and reopen this PR.

Thanks

2018-08-13 03:26 UTC, closed without merging