import-export-improvements #82 : super attribute error message improvements
magento-engcom/import-export-improvements pull request #115
Opened 2018-06-28 10:43 UTC by tadhgbowe

Improvement to product import error handling for configurable variations column super attribute codes.

### Description

If the standard product import detects that a configurable_variations attribute code is not super one the following error messages will be displayed:

Attribute code does not exist or is not in chosen attribute set.
Attribute code needs to have an Input Type of "Dropdown", "Visual Swatch" or Text Swatch"
Attribute code needs to have a Scope of "Global".

This covers all the reasons why it may not be a not super attribute. Displaying "Attribute with this code is not super" is not helpful enough.

### Fixed Issues (if relevant)

https://github.com/magento-engcom/import-export-improvements/issues/82
Please see the above issue as there is a full comment trace.

### Manual testing scenarios
Try import a configurable product with a super attribute code inside configurable_variations that:
1. doesn't exist
2. exists but is not in the target attribute set
3. is not global scope
4. Is not of type "dropdown", "visual swatch" or "text swatch"

### Contribution checklist
 - [ x ] Pull request has a meaningful description of its purpose
 - [ x ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-28 10:43 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/import-export-improvements?pullRequest=115) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/import-export-improvements?pullRequest=115) before we can accept your contribution.<br/>

2018-07-03 10:51 UTC, magento-engcom-team commented
@tadhgbowe thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-07-03 11:06 UTC, dmanners requested changes
Hey, thanks for your PR. I have added a few comments on issues. I am happy with you adding more detail for the user. Good job.

2018-07-03 11:06 UTC, dmanners commented on app/code/Magento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php
> +    protected function _identifySuperAttributeError($superAttrCode, $rowNum)
I think we could probably make this method private and remove the _ in the name. For me since this method is only being used in this class making it private would work fine. Do you think that makes sense or would you think it should be open for extension? In that case I would make it public as we are trying to stay away from protected methods.

2018-07-03 11:06 UTC, dmanners commented on app/code/Magento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php
> +        $commonAttributes = self::$commonAttributesCache;
Do we need this assignment or could we just loop through the cache directly?

2018-07-03 11:06 UTC, dmanners commented on app/code/Magento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php
> +        foreach ($commonAttributes as $attributeRow) {
Is there no way to access the attribute from the cache via the code rather than looping through all attributes. This could be a big performance hit if you have a large amount of attributes.

2018-07-03 11:06 UTC, dmanners commented on app/code/Magento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php
> +        if ($codeExists == false) {
Since we are setting these attributes let's do a === check here just to be sure we are dealing with booleans.

2018-07-03 11:06 UTC, dmanners commented on app/code/Magento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php
> +                if (!$this->_identifySuperAttributeError($superAttrCode, $rowNum)) {
Overall I like adding in this new check to give some more useful information to the user.

2018-07-03 11:06 UTC, dmanners commented on app/code/Magento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php
> +        self::ERROR_ATTRIBUTE_CODE_DOES_NOT_EXIST => 'Column configurable_variations: Attribute with code "%s" does not exist or is missing from product attribute set',
I have seen a few of these line issues before and people will format the array so the key and value are on two different lines. Would that make lines under 120 characters? Also does that make sense from your point of view?

2018-07-06 11:48 UTC, dmanners commented
@tadhgbowe there seem to be a could of static test failures now.

```
1) Magento\Test\Php\LiveCodeTest::testCodeStyle
PHP Code Sniffer detected 2 violation(s): 
FILE: ...agento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 342 | ERROR | [x] Expected 1 space after USE keyword; found 0
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
Failed asserting that 2 matches expected 0.
/home/travis/build/magento-engcom/import-export-improvements/dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php:269
2) Magento\Test\Php\LiveCodeTest::testCodeMess
PHP Code Mess has found error(s):
/home/travis/build/magento-engcom/import-export-improvements/app/code/Magento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php:331	The method identifySuperAttributeError() has a Cyclomatic Complexity of 11. The configured cyclomatic complexity threshold is 10.
```

The first one seems like not a big problem to update. The second might take a bit of refactoring on the method to see if it can be decreased a bit. If you need some help, feel free to reach out to me on that.

2018-07-06 14:04 UTC, tadhgbowe commented
@dmanners - thanks for the update earlier. Yep I noticed it too. I pushed up some enhancements (i.e. tidy up!) earlier on. Removing the foreach introduced this little beauty. There were some cyclomatic complexities too. I'm on the case... :-) 

ps. hope you've been out for fresh air ;-)

2018-07-09 08:22 UTC, dmanners commented
Hi @tadhgbowe looking good for the changes, I will check why the integration tests are timing out and get back to you on the next steps for this pr. Weekend involved plenty of fresh air and family time.

2018-07-09 08:47 UTC, tadhgbowe commented
Morning @dmanners. #NoMagentoSunday working nicely for me. Football fever over here!
Yes, I've seen the timing out thing on other pull requests. So I hope it's just a temporary blip. Grand. T

2018-07-09 08:50 UTC, dmanners commented
So I have run the internal tools and it all seems fine from the testing side, think it might just be travis. Will pass this onto our QA team now @tadhgbowe and keep you updated.

2018-07-09 09:00 UTC, tadhgbowe commented
@dmanners - That's great. Thanks for the update. I've got a few other issues to get on with. Cheers. T

2018-07-21 12:02 UTC, merged