Added $_regionCollection property to class
magento-engcom/import-export-improvements pull request #140
Opened 2018-10-26 16:31 UTC by maxalmonte14

### Description (*)
This PR fixes an error detected by PHPStan

### Fixed Issues (if relevant)
1. https://github.com/magento-engcom/import-export-improvements/issues/136

### Manual testing scenarios (*)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-26 16:31 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/import-export-improvements?pullRequest=140) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/import-export-improvements?pullRequest=140) before we can accept your contribution.<br/>

2018-10-29 12:23 UTC, dmanners requested changes

2018-10-29 12:23 UTC, dmanners commented on app/code/Magento/CustomerImportExport/Model/Import/Address.php
> +     * @var string
In this case I think the type should be `\Magento\Directory\Model\ResourceModel\Region\Collection` as the code will use the `$regionColFactory->create()` method if it is not set in the data array.

```
        $this->_regionCollection = isset(
            $data['region_collection']
        ) ? $data['region_collection'] : $regionColFactory->create();
```

2018-10-29 12:23 UTC, dmanners commented on app/code/Magento/CustomerImportExport/Model/Import/Address.php
> +    protected $_regionCollection;
I think we can also make this private here. Since this is technically a new variable.

2018-10-29 14:10 UTC, maxalmonte14 commented
@dmanners thanks for the feedback, I'll apply the changes as soon as possible. ✌️

2018-10-30 13:16 UTC, maxalmonte14 commented
Updated, rookie mistake in the docblock 😅

2018-10-30 13:47 UTC, dmanners approved these changes

2018-10-30 13:48 UTC, dmanners submitted a review, later dismissed

2018-11-08 15:30 UTC, merged