Added $connection property to class
magento-engcom/import-export-improvements pull request #141
Opened 2018-10-26 16:55 UTC by maxalmonte14

### Description (*)
This PR solves the problem addressed in https://github.com/magento-engcom/import-export-improvements/issues/137

### Fixed Issues (if relevant)
1. https://github.com/magento-engcom/import-export-improvements/issues/137: Clean Up Helper/Uploader.php

### Manual testing scenarios (*)
Run `./vendor/bin/phpstan analyse app/code/Magento/DownloadableImportExport/Helper/Uploader.php` as described in https://github.com/magento-engcom/import-export-improvements/issues/137, after this implementation the following errors shouldn't be present

```
------ --------------------------------------------------------------------------------------------------------------------------------
  Line   Uploader.php
 ------ --------------------------------------------------------------------------------------------------------------------------------
  63     Access to an undefined property Magento\DownloadableImportExport\Helper\Uploader::$connection.
 ------ --------------------------------------------------------------------------------------------------------------------------------
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-29 11:16 UTC, dmanners commented
Hello, thank you for your pull request. I will start to process this PR and get back to you if I need any more information.

2018-10-29 15:19 UTC, dmanners requested changes

2018-10-29 15:19 UTC, dmanners commented on app/code/Magento/DownloadableImportExport/Helper/Uploader.php
> +    protected $connection = [];
Actually looking into this file I cannot see this being used in this class. So what we can do here is remove this variable and the assignment in the constructor. You will have to leave the varaible in the consturctor definition but can add Add `@SuppressWarnings(PHPMD.UnusedFormalParameter)` as it will be an unused parameters. For example:


```
    /**
     * Construct
     *
     * @param \Magento\Framework\App\Helper\Context $context
     * @param \Magento\Downloadable\Helper\File $fileHelper
     * @param \Magento\CatalogImportExport\Model\Import\UploaderFactory $uploaderFactory
     * @param \Magento\Framework\App\ResourceConnection $resource
     * @param \Magento\Framework\Filesystem $filesystem
     *
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function __construct(
        \Magento\Framework\App\Helper\Context $context,
        \Magento\Downloadable\Helper\File $fileHelper,
        \Magento\CatalogImportExport\Model\Import\UploaderFactory $uploaderFactory,
        \Magento\Framework\App\ResourceConnection $resource,
        \Magento\Framework\Filesystem $filesystem
    ) {
        parent::__construct($context);
        $this->fileHelper = $fileHelper;
        $this->fileUploader = $uploaderFactory->create();
        $this->fileUploader->init();
        $this->fileUploader->setAllowedExtensions($this->getAllowedExtensions());
        $this->fileUploader->removeValidateCallback('catalog_product_image');
        $this->mediaDirectory = $filesystem->getDirectoryWrite(DirectoryList::ROOT);
    }
```

We do this to keep from breaking backwards compatibility. More information on this topic can be found on devdocs https://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/

2018-10-30 13:11 UTC, maxalmonte14 commented
Done. Interesting approach by the way!

2018-10-30 13:50 UTC, dmanners submitted a review, later dismissed

2018-11-09 08:47 UTC, sidolov requested changes

2018-11-09 08:47 UTC, sidolov commented on app/code/Magento/DownloadableImportExport/Helper/Uploader.php
> -        $this->connection = $resource->getConnection('write');
We are not allowed to [remove public properties](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/), because according to [PHP Property Visibility](http://php.net/manual/en/language.oop5.visibility.php): Methods declared without any explicit visibility keyword are defined as public.

2018-11-09 11:11 UTC, dmanners commented on app/code/Magento/DownloadableImportExport/Helper/Uploader.php
> -        $this->connection = $resource->getConnection('write');
Ah forgot about that. @maxalmonte14 would you be able to add the `$connection` as public then in future versions we can deprecate it. But it would be better at least to have it shown and public now. Thanks

2018-11-09 12:37 UTC, maxalmonte14 commented on app/code/Magento/DownloadableImportExport/Helper/Uploader.php
> -        $this->connection = $resource->getConnection('write');
Should I add the property as public with a default null value, or should I leave the implementation as before?

2018-11-09 12:58 UTC, dmanners commented on app/code/Magento/DownloadableImportExport/Helper/Uploader.php
> -        $this->connection = $resource->getConnection('write');
I would add the property without a default and then put this implementation back as it was before. Unless @sidolov thinks best otherwise.

2018-11-10 15:07 UTC, maxalmonte14 commented on app/code/Magento/DownloadableImportExport/Helper/Uploader.php
> -        $this->connection = $resource->getConnection('write');
Done, now the `$connection` property is public.

2018-11-16 14:50 UTC, dmanners requested changes

2018-11-16 14:50 UTC, dmanners commented on app/code/Magento/DownloadableImportExport/Helper/Uploader.php
> +     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
I guess now we do not need this suppress warning since the connection is being set.

2018-11-16 15:03 UTC, maxalmonte14 commented on app/code/Magento/DownloadableImportExport/Helper/Uploader.php
> +     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
Done.

2018-11-26 10:42 UTC, dmanners approved these changes

2018-12-06 16:46 UTC, merged