Added $websiteString property to test class
magento-engcom/import-export-improvements pull request #142
Opened 2018-10-26 17:04 UTC by maxalmonte14

### Description (*)
This PR solves the problem addressed in https://github.com/magento-engcom/import-export-improvements/issues/132

### Fixed Issues (if relevant)
1. https://github.com/magento-engcom/import-export-improvements/issues/132: 
Clean up app/code/Magento/AdvancedPricingImportExport/Test/Unit/Model/Import/AdvancedPricing/Validator/WebsiteTest.php

### Manual testing scenarios (*)
1. Run `./vendor/bin/phpstan analyse app/code/Magento/AdvancedPricingImportExport/Test/Unit/Model/Import/AdvancedPricing/Validator/WebsiteTest.php`as described in https://github.com/magento-engcom/import-export-improvements/issues/132, after this implementation the following error shouldn't be present

```
------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Line   WebsiteTest.php                                                                                                                                                                     
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  106    Access to an undefined property Magento\AdvancedPricingImportExport\Test\Unit\Model\Import\AdvancedPricing\Validator\WebsiteTest::$websiteString.                                   
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-29 11:16 UTC, dmanners commented
Hello, thank you for your pull request. I will start to process this PR and get back to you if I need any more information.

2018-10-29 15:22 UTC, dmanners requested changes

2018-10-29 15:22 UTC, dmanners commented on app/code/Magento/AdvancedPricingImportExport/Test/Unit/Model/Import/AdvancedPricing/Validator/WebsiteTest.php
> +    protected $websiteString;
After looking into the usage of this it seems to only be used in one method. I would suggest in this case we convert it to a local variable to the function. Something like:

```
        $websiteString = $this->getMockBuilder(
            \Magento\AdvancedPricingImportExport\Model\Import\AdvancedPricing\Validator\Website::class
        )
            ->setMethods(['_clearMessages', '_addMessages'])
            ->setConstructorArgs([$this->storeResolver, $this->webSiteModel])
            ->getMock();
        $result = $websiteString->getAllWebsitesValue();
```

After making this change please also run the unit test to make sure it is not failing. This can be done via the command:

`./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/AdvancedPricingImportExport/Test/Unit/Model/Import/AdvancedPricing/Validator/WebsiteTest.php`

2018-10-30 13:03 UTC, maxalmonte14 commented
I extracted the `$websiteString` to a local variable inside the `testGetAllWebsitesValue` method, also I made sure the test is passing by running `./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/AdvancedPricingImportExport/Test/Unit/Model/Import/AdvancedPricing/Validator/WebsiteTest.php` 👍

2018-10-30 13:53 UTC, dmanners approved these changes

2018-11-06 18:07 UTC, merged