Added $_customerCollection property to Storage class
magento-engcom/import-export-improvements pull request #144
Opened 2018-10-26 17:31 UTC by maxalmonte14

### Description (*)
This PR solves the problem addressed in https://github.com/magento-engcom/import-export-improvements/issues/135

### Fixed Issues (if relevant)
1. https://github.com/magento-engcom/import-export-improvements/issues/135: Clean up Model/ResourceModel/Import/Customer/Storage.php

### Manual testing scenarios (*)
1. Run `./vendor/bin/phpstan analyse app/code/Magento/CustomerImportExport/Model/ResourceModel/Import/Customer/Storage.php` as described in https://github.com/magento-engcom/import-export-improvements/issues/135, after this implementation the following error shouldn't be present

```
------ -----------------------------------------------------------------------------------------------------------------------------------------------------------
  Line   Storage.php
 ------ -----------------------------------------------------------------------------------------------------------------------------------------------------------
  61     Access to an undefined property Magento\CustomerImportExport\Model\ResourceModel\Import\Customer\Storage::$_customerCollection.
 ------ -----------------------------------------------------------------------------------------------------------------------------------------------------------
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-29 11:16 UTC, dmanners commented
Hello, thank you for your pull request. I will start to process this PR and get back to you if I need any more information.

2018-10-29 15:32 UTC, dmanners requested changes

2018-10-29 15:32 UTC, dmanners commented on app/code/Magento/CustomerImportExport/Model/ResourceModel/Import/Customer/Storage.php
> +    private $_customerCollection;
Interestingly I cannot see this being used in this class and in fact during the method `prepareCollection` uses the `$this->customerCollectionFactory->create()` method to create it's collection. I would suggest that we can remove this variable and the assignment in the `__constuct`

2018-10-30 12:47 UTC, maxalmonte14 commented
Done, I removed the unused properties and made sure that `StorageTest.php` is passing, by running `vendor/bin/phpunit app/code/Magento/CustomerImportExport/Test/Unit/Model/ResourceModel/Import/Customer/StorageTest.php` 👍

2018-10-30 13:06 UTC, dmanners commented
Nice @maxalmonte14 I will update our tools and progress this.

2018-10-30 13:11 UTC, dmanners requested changes

2018-10-30 13:11 UTC, dmanners commented on app/code/Magento/CustomerImportExport/Model/ResourceModel/Import/Customer/Storage.php
> -        CustomerCollectionFactory $collectionFactory,
So we still need this variable passed in as it get's used on `$this->customerCollectionFactory = $collectionFactory;` so we should keep that as well as `private $customerCollectionFactory;` but we can keep the removal of:

```
        $this->_customerCollection = isset(
            $data['customer_collection']
        ) ? $data['customer_collection'] : $collectionFactory->create();
```

2018-10-30 13:23 UTC, maxalmonte14 commented
I added back the `customerCollectionFactory` property to the class and the parameter to the constructor method, I didn't realize the mistake in the first place, sorry!

2018-10-30 13:44 UTC, dmanners submitted a review, later dismissed
Thanks for the speedy update.

2018-11-09 08:48 UTC, sidolov requested changes

2018-11-09 08:48 UTC, sidolov commented on app/code/Magento/CustomerImportExport/Model/ResourceModel/Import/Customer/Storage.php
> -        $this->_customerCollection = isset(
We are not allowed to [remove public properties](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/), because according to [PHP Property Visibility](http://php.net/manual/en/language.oop5.visibility.php): Methods declared without any explicit visibility keyword are defined as public.

2018-11-09 11:12 UTC, dmanners commented on app/code/Magento/CustomerImportExport/Model/ResourceModel/Import/Customer/Storage.php
> -        $this->_customerCollection = isset(
Sorry @maxalmonte14 would you be able to add the `$_customerCollection` as public then in future versions we can deprecate it. But it would be better at least to have it shown and public now. Thanks

2018-11-10 14:53 UTC, maxalmonte14 commented on app/code/Magento/CustomerImportExport/Model/ResourceModel/Import/Customer/Storage.php
> -        $this->_customerCollection = isset(
Done, now the $_customerCollection property is public.

2018-12-06 16:46 UTC, merged