Fix "no file extension at url" issue
magento-engcom/import-export-improvements pull request #151
Opened 2018-10-28 23:10 UTC by Stepa4man

Fix "no file extension at url" issue

### Description (*)
Magento checks headers for content type and takes file extension 

### Fixed Issues
1. https://github.com/magento-engcom/import-export-improvements/issues/78

### Manual testing scenarios (*)
Described in issue

### Note
Content disposition not used because it's not actually all the time in headers.

2018-10-28 23:10 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento-engcom/import-export-improvements?pullRequest=151) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/import-export-improvements?pullRequest=151) before we can accept your contribution.<br/><hr/>**Stepan Furman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-10-29 10:19 UTC, dmanners requested changes
Thanks for this PR. I have a few questions on this PR. Looks like a good start and will hopefully improve the system.

2018-10-29 10:19 UTC, dmanners commented on app/code/Magento/CatalogImportExport/Model/Import/Uploader.php
> +        $contentTypeExploded = explode('/', get_headers($this->httpScheme . $url, 1)['Content-Type']);
I would like to add a check here to make sure that `['Content-Type']` exists before just we try to use it.

2018-10-29 10:19 UTC, dmanners commented on app/code/Magento/CatalogImportExport/Model/Import/Uploader.php
> +        return in_array(end($fileNameExploded), array_keys($this->_allowedMimeTypes));
Nice that for adding this check to make sure extension is allowed. Though if the name is not an allowed mimtype should we move on in the `getFileNameWithExtension` or should we error and stop the processing?

2018-10-29 10:19 UTC, dmanners commented on app/code/Magento/CatalogImportExport/Model/Import/Uploader.php
> +        $contentTypeExploded = explode('/', get_headers($this->httpScheme . $url, 1)['Content-Type']);
Also since we have `allowedMimeTypes` should we also check the content-type of images is also allowed?

2018-10-29 10:20 UTC, dmanners commented
Hi @Stepa4man could you check the git user to make sure it matched your github user and sign the CLA.

Also please take a look at my feedback and the untitest failures.

https://travis-ci.org/magento-engcom/import-export-improvements/jobs/447558203

2018-10-29 12:31 UTC, Stepa4man commented
Hey @dmanners, thanks for your comments. I'll take a look and fix/answer as soon as possible.

2018-10-30 19:44 UTC, Stepa4man commented on app/code/Magento/CatalogImportExport/Model/Import/Uploader.php
> +        $contentTypeExploded = explode('/', get_headers($this->httpScheme . $url, 1)['Content-Type']);
> Also since we have `allowedMimeTypes` should we also check the content-type of images is also allowed?

![image](https://user-images.githubusercontent.com/15912461/47745658-d876da00-dc8c-11e8-901d-bc9728865d48.png)

Validation will be performed later at the "move()" function, so no needs to duplicate it

> I would like to add a check here to make sure that `['Content-Type']` exists before just we try to use it.

I'll add it.

2018-10-30 19:59 UTC, Stepa4man commented on app/code/Magento/CatalogImportExport/Model/Import/Uploader.php
> +        return in_array(end($fileNameExploded), array_keys($this->_allowedMimeTypes));
The same here -> alidation will be performed later at the "move()" function, so no needs to duplicate it

But I have added throw this exception, so we will have particular error message right now:
` else {
            throw new LocalizedException(__("File doesn't contain extension or Content-type header"));
}`

2018-10-31 10:56 UTC, dmanners commented
So @Stepa4man thanks for the update. Let me take a look at the unit tests and see what I can find out. Currently there is the following errors.

```
There were 2 errors:
1) Magento\CatalogImportExport\Test\Unit\Model\Import\UploaderTest::testMoveFileUrl with data set #0 ('http://test_uploader_file', 'test_uploader_file', 'test_uploader_file')
PHPUnit\Framework\Exception: Warning: get_headers(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/travis/build/magento-engcom/import-export-improvements/app/code/Magento/CatalogImportExport/Model/Import/Uploader.php:400.
/home/travis/build/magento-engcom/import-export-improvements/dev/tests/unit/framework/bootstrap.php:54
/home/travis/build/magento-engcom/import-export-improvements/app/code/Magento/CatalogImportExport/Model/Import/Uploader.php:400
/home/travis/build/magento-engcom/import-export-improvements/app/code/Magento/CatalogImportExport/Model/Import/Uploader.php:376
/home/travis/build/magento-engcom/import-export-improvements/app/code/Magento/CatalogImportExport/Model/Import/Uploader.php:181
/home/travis/build/magento-engcom/import-export-improvements/app/code/Magento/CatalogImportExport/Test/Unit/Model/Import/UploaderTest.php:133
2) Magento\CatalogImportExport\Test\Unit\Model\Import\UploaderTest::testMoveFileUrl with data set #1 ('https://!:^&`;file', '!:^&`;file', 'file')
PHPUnit\Framework\Exception: Warning: get_headers(http://!:^&`;file): failed to open stream: operation failed in /home/travis/build/magento-engcom/import-export-improvements/app/code/Magento/CatalogImportExport/Model/Import/Uploader.php:400.
/home/travis/build/magento-engcom/import-export-improvements/dev/tests/unit/framework/bootstrap.php:54
/home/travis/build/magento-engcom/import-export-improvements/app/code/Magento/CatalogImportExport/Model/Import/Uploader.php:400
/home/travis/build/magento-engcom/import-export-improvements/app/code/Magento/CatalogImportExport/Model/Import/Uploader.php:376
/home/travis/build/magento-engcom/import-export-improvements/app/code/Magento/CatalogImportExport/Model/Import/Uploader.php:181
/home/travis/build/magento-engcom/import-export-improvements/app/code/Magento/CatalogImportExport/Test/Unit/Model/Import/UploaderTest.php:133
```

2018-11-24 05:30 UTC, naydav commented on app/code/Magento/CatalogImportExport/Model/Import/Uploader.php
> +    private function isFileNameHasExtension($fileName)
The method should have a more proper name like 'isAllowesFileNameExtension' (according to implementation)
Also, looks like we can use `pathinfo($path , \PATHINFO_EXTENSION);`

2018-11-24 05:37 UTC, naydav commented on app/code/Magento/CatalogImportExport/Model/Import/Uploader.php
> +        return end($contentTypeExploded);
Why don't we check the file type from the header (according to allowed formats in `$this->_allowedMimeTypes`)?

2019-04-09 08:51 UTC, closed without merging